"""
Quant / Momentum Score Engine (§33A). Deterministic, 0-100, NEVER
generated by Claude (§36). Every component is normalized 0-100 before
weighting; the final score is clamped to 0-100.

Per §33A.1.8: a required component that cannot be reliably calculated
must never be silently defaulted to 0 — it must block the whole score
(the caller/Signal Engine turns "not computable" into NO_TRADE, never
"computable at a fabricated 0").
"""

from __future__ import annotations

from dataclasses import dataclass, field

from app.config.settings import StrategyConfig
from app.features import feature_engine as fe
from app.features.store import SymbolFeatureState
from app.signals import friction as friction_mod

EPSILON = 1e-9


def clamp01(x: float) -> float:
    return max(0.0, min(1.0, x))


def normalize(value: float, floor: float, ceiling: float) -> float:
    """Every §33A.1.x component: 100 * clamp((value - floor) / (ceiling - floor), 0, 1)."""
    span = ceiling - floor
    if abs(span) <= EPSILON:
        return 0.0
    return 100.0 * clamp01((value - floor) / span)


@dataclass
class ComponentAudit:
    name: str
    component_value: float | None
    normalized_score: float | None
    normalization_floor: float
    normalization_ceiling: float


@dataclass
class QuantScoreResult:
    computable: bool
    missing_components: list[str] = field(default_factory=list)
    quant_score: float | None = None
    components: list[ComponentAudit] = field(default_factory=list)
    # Raw values worth carrying forward to the Signal Engine so it
    # doesn't have to recompute the Feature Engine outputs a second time.
    rvol: float | None = None
    trade_acceleration: float | None = None
    net_taker_delta: float | None = None
    momentum_ratio: float | None = None
    breakout: fe.BreakoutInputs | None = None
    dollar_volume_24h: float | None = None
    atr_1m: float | None = None
    reference_friction_coverage: float | None = None


def compute_quant_score(
    state: SymbolFeatureState,
    current_price: float,
    strategy: StrategyConfig,
) -> QuantScoreResult:
    missing: list[str] = []
    components: list[ComponentAudit] = []

    def audit(name: str, value: float | None, floor: float, ceiling: float) -> float | None:
        score = normalize(value, floor, ceiling) if value is not None else None
        components.append(ComponentAudit(name, value, score, floor, ceiling))
        if value is None:
            missing.append(name)
        return score

    rvol_value = fe.rvol(state)
    rvol_score = audit("rvol", rvol_value, strategy.rvol_score_floor, strategy.rvol_score_ceiling)

    accel_value = fe.trade_acceleration(state)
    accel_score = audit("acceleration", accel_value, strategy.acceleration_score_floor, strategy.acceleration_score_ceiling)

    delta_value = fe.net_taker_delta(state)
    delta_score = audit("delta", delta_value, strategy.delta_score_floor, strategy.delta_score_ceiling)

    momentum_value = fe.momentum_ratio(state, window_minutes=strategy.momentum_window_minutes)
    momentum_score = audit("momentum", momentum_value, strategy.momentum_score_floor, strategy.momentum_score_ceiling)

    breakout = fe.breakout_inputs(state, current_price, strategy)
    breakout_distance = breakout.breakout_distance_atr if breakout else None
    breakout_score = audit(
        "breakout", breakout_distance,
        strategy.breakout_atr_multiplier,  # Breakout_Floor LOCKED == breakout_atr_multiplier (§33A.1.5.1)
        strategy.breakout_score_ceiling,
    )

    dollar_volume = fe.dollar_volume_24h(state)
    liquidity_score = audit("liquidity", dollar_volume, strategy.min_24h_volume_usd, strategy.liquidity_score_ceiling_usd)

    atr = fe.atr_1m(state)
    range_1m_value = fe.range_1m(state)
    volume_1m = fe.volume_1m_usd(state)
    spread = fe.spread_percent(state)

    reference_friction_coverage: float | None = None
    if atr is not None and range_1m_value is not None and volume_1m is not None and spread is not None and current_price > EPSILON:
        ref_slippage = friction_mod.estimated_slippage_percent(
            order_size_usd=strategy.reference_order_size_usd,
            range_1m=range_1m_value, atr_1m=atr, volume_1m_usd=volume_1m,
            base_slippage_percent=strategy.base_slippage_percent, gamma=strategy.slippage_gamma,
        )
        ref_total_friction = friction_mod.total_friction_percent(strategy.taker_fee_percent, spread, ref_slippage)
        ref_risk_per_unit = strategy.sl_atr_multiplier * atr
        ref_expected_move = strategy.take_profit_rr * ref_risk_per_unit
        # Percent-POINTS convention (see app/signals/exit_levels.py) —
        # must match friction's units for the ratio to mean anything.
        ref_expected_move_percent = (ref_expected_move / current_price) * 100
        reference_friction_coverage = friction_mod.friction_coverage(ref_expected_move_percent, ref_total_friction)

    friction_score = audit("friction", reference_friction_coverage, strategy.friction_score_floor, strategy.friction_score_ceiling)

    if missing:
        return QuantScoreResult(computable=False, missing_components=missing, components=components)

    weights = strategy.quant_score_weights
    quant_score = (
        weights.rvol * rvol_score
        + weights.acceleration * accel_score
        + weights.delta * delta_score
        + weights.momentum * momentum_score
        + weights.breakout * breakout_score
        + weights.liquidity * liquidity_score
        + weights.friction * friction_score
    )
    quant_score = max(0.0, min(100.0, quant_score))

    return QuantScoreResult(
        computable=True,
        quant_score=quant_score,
        components=components,
        rvol=rvol_value, trade_acceleration=accel_value, net_taker_delta=delta_value,
        momentum_ratio=momentum_value, breakout=breakout, dollar_volume_24h=dollar_volume,
        atr_1m=atr, reference_friction_coverage=reference_friction_coverage,
    )


def classify_quant_score(score: float, strategy: StrategyConfig) -> str:
    """§33A interpretation bands."""
    t = strategy.quant_score_thresholds
    if score >= t.high_conviction:
        return "high_conviction"
    if score >= t.pump_detected:
        return "pump_detected"
    if score >= t.candidate:
        return "candidate"
    if score >= t.watch:
        return "watch"
    return "no_trade"
